services:
  # Blue environment
  web-blue:
    image: nginx:1.27-alpine-slim
    configs:
      - source: blue_conf
        target: /etc/nginx/conf.d/default.conf
      - source: blue_index
        target: /var/www/html/index.html
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
    networks:
      - bleu_green

  # Green environment
  web-green:
    image: nginx:1.27-alpine-slim
    configs:
      - source: green_conf
        target: /etc/nginx/conf.d/default.conf
      - source: green_index
        target: /var/www/html/index.html
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
    networks:
      - bleu_green

  # NGINX load balancer
  loadbalancer:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
    ports:
      - "8383:80"
    configs:
      - source: loadbalancer_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - bleu_green
    depends_on:
      - blue-app
      - green-app

configs:
  blue_conf:
    file: ./nginx/blue/conf.d/default.conf
  blue_index:
    file: ./nginx/blue/html/index.html
  green_conf:
    file: ./nginx/green/conf.d/default.conf
  green_index:
    file: ./nginx/green/html/index.html
  loadbalancer_conf:
    name: default-${SETTINGS_TIMESTAMP}.conf
    file: ./nginx/loadbalancer/conf.d/default.conf

networks:
  bleu_green:
    driver: overlay
